[toolchain]
channel = "nightly-2025-01-07"
profile = "minimal"
components = [
    "rustfmt",
    "clippy-preview",
    "rust-analyzer",
    # "miri",
    "rustc-codegen-cranelift-preview",
    "llvm-tools-preview",
]
